workflow/project/delete_usecase.js
workflow/project/getProjectsUsecases.js
workflow/task/getTaskDetails.js
workflow/usecase/usecase_search.js

Moved the query parameters validation just after the event.

refactor:made minor changes

---

workflow/serverless.yml
workflow/usecase/getUsecaseStatus.js

API name : getUsecaseStatus
Method: GET
Description: This API retrieves information about a specific use case, including details about the assigned resource and the number of tasks performed by the resource.
queryStringParameter : usecase_id 
API Responce :
``` json
{
"usecase_id": "bc4ea755-7819-4f2f-9afe-19932684fa6c",
"usecase_name": "first usecase",
"usecase_status": "",
"usecase_current_stage": "",
"workflow_id": "aeb49895-d666-42e3-93c9-335ff0115921",
"workflow_name": "workflow_name",
"stageNames": [
"stage_1",
"stage_2"
],
"resources": [
{
"resource_name": "Jack Robinson",
"role": "UI Developer",
"total_tasks": "1",
"current_task": "",
"image": "https://cdn.pixabay.com/photo/2016/03/26/20/35/young-man-1281282_640.jpg",
"assigned_date": "",
"planned_start_date": "", …
```

added getUsecaseStatus api

---

workflow/project/getProjectsWorkflows.js
workflow/project/projectsResourcesTasksStatus.js
workflow/pseudocode.md
workflow/resource/getResources.js
workflow/resource/resourceListView.js
workflow/serverless.yml

1. API name : getResources
Method: GET
Description: This API retrieves information about resources and their associated projects, and can filter results based on a specified project ID in an HTTP request.
queryStringParameter : project_id (optional)
API Responce : 
```json
[
{
"resource_id": "9388945f-f6a7-459e-ba74-f31c08272478",
"resource_name": "John Doe",
"role": "Developer",
"resource_img_url": "",
"resource_email": "john.doe@example.com",
"projects": [
{
"project_id": "fc225aa6-1453-4adc-b316-e55b65ea3475",
"project_name": "Workflow",
"project_img_url": "url"
}
]
},
{
"resource_id": "bc8ddbcc-914c-45ab-9577-5c7e84bf40d6",
"resource_name": "chetan",
"role": "backend_developer",
"resource_img_url": "",
"resource_email": "chetan@example.com",
"projects": [
{
"project_id": …
```

feat: Updated getResources API

---

workflow/dashboard/getResourcesTasksStatus.js

getResourcesTaskStatus API Testing 
DefaultCase:
API Response :
getting the taskstatus in last 30 days of all the resources
No Issues
DatesFilter:
API Response :
getting taskstatus between dates of all the resources
NO Issues
resource_id filter:
API Response :
getting taskstatus of a given resource_id between dates
NO Issues
Changes I have made:
-> changed database connection
-> removed reduntant code and comments
-> changed error statuscode to 500
-> closed db in finally block

refactored and completed testing getResourcesTaskStatus api

---

workflow/dashboard/getProjectsOverview.js
workflow/pseudocode.md

This API will take the request from params project status 
Request params :
project_status :" string "
Response :
```json
[
{
"project_id": "aa7ebae7-8775-4d95-8bfb-00d48e33e2ec",
"project_name": "CMS",
"status": "completed",
"total_usecases": "3",
"completed_usecases": "0",
"due_date": "12-12-2024",
"completed_tasks_percentage": 44
},
{
"project_id": "c5498557-b706-4019-b3e7-2e0fb6415577",
"project_name": "Workflow",
"status": "completed",
"total_usecases": "3",
"completed_usecases": "2",
"due_date": "12-12-2024",
"completed_tasks_percentage": 44
}
]
```

feat:Updated API & db connector

---

workflow/dashboard/getProjectsUsecaseOverview.js

APi name : getProjectUsecaseOverview
Method: GET 
Request queryparams :
project_id : uuid
Response : 
``` json
[
{
"project_id": "99424866-b423-4c15-afcc-a136622a9240",
"project_name": "workflow",
"completed": "1",
"incomplete": 2
}
]
```

updated getProjectUsecaseOverview API

---

workflow/dashboard/getOrgProjectsOverview.js

API name : getOrgProjectsOverview
Method: GET
Description: This API retrieves information about count by total projects,total tasks,percentage completed projects are given
API Responce :
``` json
{
"total_projects": "27",
"total_tasks": "6",
"percentage_completed": 0,
"completed": "0",
"in_progress": "2",
"unassigned": "25"
}
```
Changes I have made:
-> I have merged three queries
-> changed database connection
-> changed error statuscode to 500
-> closed db in finally block

refactor code tested getOrgProjectsOverview api

---

workflow/serverless.yml
workflow/usecase/getUsecases.js

1. API name : getUsecases
Method: GET
Description: This API retrieves Usecases of a workflow for a particular project , and can filter results based on a specified usecase name in an HTTP request.
queryStringParameter : project_id, workflow_id, and usecase_name (optional)
API Responce : 
```json
[
{
"usecase_id": "ea6e96af-f511-4d3e-991f-89a42f022cde",
"usecase_name": "usecase_name2",
"current_stage": "stage_name",
"assignee_id": "ab6c9a69-e476-424d-8072-e43a8d824af1",
"assignee_name": "Jon",
"total_resources": 4,
"start_date": "date",
"end_date": "date"
},
{
"usecase_id": "d06b4b24-d5c1-4b25-9dd8-2d7fabfd11fa",
"usecase_name": "usecase_name",
"current_stage": "stage_name",
"assignee_id": "0a7a09f7-e906-452c-87c0-f81549756b08",
"assignee_name": "Peter",
"total_resources": 4,
"start_date": …
```

getUsecases API

---

workflow/serverless.yml
workflow/usecase/getUsecase.js

Configured serverless.yml file for getUsecase API:
``` json
getUsecase :
handler: usecase/getUsecase.handler
role: ${env:LAMBDA_ROLE}
events:
- http:
path: /usecase/{id}
method: get
cors: true
``` 
Added else logic if there are no tasks for particular stage then push empty tasks array
``` json
if (taskGroups.hasOwnProperty(stageName)) {
stage[stageName].tasks = taskGroups[stageName];
} else {
stage[stageName].tasks = [ ];
}
``` 
Removed project_id,workflow_id from response
``` json
{
"usecase_id": "36be72c2-f1f2-4b5e-a3cc-b172a25d8b19",
"assignee_id": "4789fd43-b892-49f8-a3f8-dae58c87888a",
"assignee_name": "Jack Robinson",
"role": "UI Developer",
"image": "https://cdn.pixabay.com/photo/2016/03/26/20/35/young-man-1281282_640.jpg",
"current_task": {
"task_id": "",
"task_name": ""
}, …
```

Update : serverless.yml file and if else logic, removed workflow_id , project_id fields from response

---

workflow/usecase/getUsecases.js

removed usecase_name filter from getUsecases API.

chore : removed usecase_name filter from getUsecases API

---

workflow/serverless.yml
workflow/usecase/updateUsecase.js

this api will updates the stages and it creates the new version of the state machine 
Request pathParams:
id : "" (usecaseId)
Request body : 
````json
{
"name": "string",
"updated_by_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"stages": [
{
"additionalProp1": {
"tasks": [
"string"
],
"checklists": [
"string"
]
},
"additionalProp2": {
"tasks": [
"string"
],
"checklists": [
"string"
]
},
"additionalProp3": {
"tasks": [
"string"
],
"checklists": [
"string"
]
}
}
]
}
````
Response : 
```json
{
"stages": [
{
"additionalProp1": {
"tasks": [
"string"
],
"checklists": [
"string"
]
},
"additionalProp2": {
"tasks": [
"string"
],
"checklists": [
"string"
]
},
"additionalProp3": {
"tasks": [
"string"
],
"checklists": [
"string"
]
}
}
]
}
```

Updateusecase API 

---

workflow/serverless.yml
workflow/workflow/getAllWorkflows.js

API name: getAllWorkflows
Method: GET
Description: This API is to get the list workflows to the inside project. Giving the project_id in the params.
queryStringParameter: project_id (required)
Request body :
``` json
[
{
"workflow_id": "12746fac-d5c6-493b-bc18-f257468f0283",
"workflow_name": "workflow2",
"total_usecases": "5",
"task_completed": null
},
{
"workflow_id": "297ecebd-8cb1-4ce4-b797-7cfc85735f6b",
"workflow_name": "workflow-5",
"total_usecases": "6",
"task_completed": null
},
{
"workflow_id": "2ffd276c-0f27-49ab-bbc0-87dd5078c545",
"workflow_name": "workflow3",
"total_usecases": "1",
"task_completed": null
},
{
"workflow_id": "b0c554bb-fb58-435b-867a-51d8ed9e60bc",
"workflow_name": "workflow4",
"total_usecases": "15",
"task_completed": null
},
{
"workflow_id": …
```

adding new api:getAllWorkflows

---

workflow/serverless.yml
workflow/usecase/deleteUsecase.js
workflow/workflow/deleteWorkflow.js

**API name:** deleteWorkflow 
**Method:** DELETE
**Description:** The primary functionality of this api is to delete statemachine  of the corresponding workflow based on the id of the workflow.Then update the status field of the workflow to terminate also also check if the response of the DeleteStatemachineCommand returns status code 200, if not rollback the database query.  
**pathParameter:** id (required)
```json
"workflow sent for deletion and updated workflow status success"
```

feat:added deleteWorkflow API,minor changes in deleteUsecase

---

workflow/serverless.yml
workflow/workflow/updateWorkflow.js

**API name:** updateWorkflow 
**Method:** PUT
**Description:** The primary functionality of this API is to update a state machine associated with a workflow in an AWS Step Functions (SFN) service. The API expects an HTTP request with a specified **id** path parameter, representing the unique identifier of the workflow. The request body should contain information about the updates to be applied to the workflow, including the **updated_by_id** and **stages**.
**pathParameter:** id (required)
**Request body :** 
```json 
{
"updated_by_id": "8f68647c-5249-4748-8464-d0daa2f55e2c",
"stages": [
{
"collect-money": {
"tasks": [
"task-1",
"task-2",
"task-3"
],
"checklist": [
"thing 1",
"thing 2",
"thing 3"
]
}
},
{
"spend-money": {
"tasks": [
"mytask-1",
"task-2",
"task-3",
"task-4"
],
"checklist": …
```

feat:Created updateWorkflow API

---

workflow/usecase/updateUsecase.js

update usecase api 
Request pathparams :
id (usecaseid)
request body:
```json
{
"name": "workflow1",
"updated_by_id": "30ae6a64-5197-4aa4-bd0a-0bf986741a74",
"stages":[
{
"Requirements": {
"tasks": [
"task-1",
"task-3"
],
"checklist": [
"thing 1",
"thing 3"
]
}
},
{
"mock": {
"tasks": [
"mytask-1",
"task-2",
"task-3"
],
"checklist": [
"thing 1",
"thing 2",
"thing 3"
]
}
}
]
}
````
Response :
```json
{
"stages": [
{
"Requirements": {
"tasks": [
"task-1",
"task-3"
],
"checklist": [
"thing 1",
"thing 3"
]
}
},
{
"mock": {
"tasks": [
"mytask-1",
"task-2",
"task-3"
],
"checklist": [
"thing 1",
"thing 2",
"thing 3"
]
}
}
]
}
```

feat:Updatedusecase API

---

workflow/serverless.yml
workflow/task/getTask.js

API name: getTask
Method: GET
Description: This API is to get the task id,task status,task end date from tasks_table. Giving the task_id in params.
pathParameter: task_id (required)
Request body :
``` json
{
"id": "fb01fcd8-208a-47c1-b1da-c0e1973fe55b",
"status": "In Progress",
"end_date": "2023-01-20",
"start_date": "2023-01-10",
"created_date": "2023-01-05",
"resource_end_date": "2023-01-18",
"resource_start_date": "2023-01-08"
}
```

adding new api getTask

---

workflow/serverless.yml
workflow/task/addComment.js
workflow/usecase/deleteUsecase.js
workflow/usecase/getUsecase.js
workflow/workflow/deleteWorkflow.js

**API name:** addComment 
**Method:** PUT
**Description:**  This api updates every comment created on the task into comments column.Every comment has the following structure 
```json
{
"reply": {},
"comment": "updatedd",
"resource": {
"id": "26a677d9-133c-4f34-a553-5d977fd5f7f9",
"name": "shiva",
"image_url": ""
},
"created_date": "2024-01-29T07:15:08.073Z"
}
```
**pathParameter:** id (required)
**Request body :** 
```json 
{
"id": "26a677d9-133c-4f34-a553-5d977fd5f7f9",
"comment": "second"
}
```
```json
comment added
```

feat:added addComment API

---

workflow/project/addProject.js
workflow/serverless.yml

add project api 
request body : 
```json
{
"project_name": "string",
"project_description": "string",
"department": "string",
"start_date": "2024-01-29",
"end_date": "2024-01-29",
"image_url": "string"
}
```
response : 
```json
{
"name": "string3",
"status": "",
"project_manager": {
"id": "",
"name": "",
"image_url": ""
},
"project_description": "string",
"department": "string",
"project_icon_url": "string",
"current_stage": "",
"start_date": "2024-01-29",
"end_date": "2024-01-29",
"budget": "",
"updated_by": {
"id": "",
"name": "",
"image_url": "",
"timestamp": ""
},
"workflows": [],
"team": {},
"id": "e98dfdea-0fbb-4738-acef-1959690131b7"
}
```

 feat : add project api

---

workflow/project/projectsResourcesTasksStatus.js

API projectsResourcesTasksStatus will gets the all the resource tasks details which are present in the project teams 
Request : 
queryStringparameters (project_id): 
Response body : 
```json
[
{
"resource_id": "30ae6a64-5197-4aa4-bd0a-0bf986741a74",
"resource_name": "Olivia Martin",
"completed": "0",
"inprogress": "0",
"pending": "0"
},
{
"resource_id": "3373514c-6590-4d0f-89cf-c4e17751a1ff",
"resource_name": "Kelly Adams",
"completed": "0",
"inprogress": "0",
"pending": "0"
},
{
"resource_id": "5aa51a3f-b8f6-4576-a105-598edc57ff2e",
"resource_name": "Nathan Brown",
"completed": "0",
"inprogress": "0",
"pending": "0"
},
{
"resource_id": "8f68647c-5249-4748-8464-d0daa2f55e2c",
"resource_name": "Mia Lopez",
"completed": "0",
"inprogress": "0",
"pending": "0"
}
]
```

projectsResourcesTasksStatus UpdatedAPI

---

workflow/task/addComment.js
workflow/usecase/addusecase.js
workflow/usecase/deleteUsecase.js
workflow/usecase/getUsecase.js
workflow/usecase/getUsecases.js
workflow/usecase/updateUsecase.js
workflow/workflow/updateWorkflow.js

**Zod Validation for Usecase  API's**
**Description:** Passing correct queryStringParameters,pathParameters, request body are very crucial to get the correct response. So to check the input parameters and body used zod validation, if the fields are not as per the defined schema, handled those issues and returned meaningful messages.
Made minor changes for addComment ,updateWorkflow API's.

feat:added zod validation for request params and body

---

workflow/workflow/function.yml
workflow/workflow/getAllWorkflows.js

**API name:** getAllWorkflows
**Method:** get
**Description:**  This api gets all the workflows from the workflows_table in the form of array of objects , each workflow object contain name,id,stages fields. This data can be used for creating workflow templates.
```json
[
{
"id": "be9c621f-8a63-4748-9143-4801fdbc9cea",
"name": "The-latest-workflow-by-team",
"stages": [
{
"Requirements1": {
"tasks": [
"task-1",
"task-2",
"task-3"
],
"checklist": [
"thing 1",
"thing 2",
"thing 3"
]
}
},
{
"mock1": {
"tasks": [
"mytask-1",
"task-2",
"task-3"
],
"checklist": [
"thing 1",
"thing 2",
"thing 3"
]
}
}
]
},
{
"id": "0a31aeb5-4a2d-4889-8b65-d6c425cd7f0f",
"name": "Testing-workflow-for-api",
"stages": [
{
"Requirements1": {
"tasks": [
"task-1",
"task-2",
"task-3"
],
"checklist": [ …
```

feat: added getAllWorkflows API for templates feature

---

workflow/usecase/function.yml
workflow/usecase/getUsecaseForm.js

this API get the usecaseform  from the db 
pathparameters :
id : usecaseid :
response body :
```json
[
{
"Requirements1": {
"assignee_id": "",
"description": "",
"start_date": "",
"end_date": "24-02-01T05:51:02.768Z",
"task_details": [
{
"id": "9f16e912-17fb-414f-b0ae-9ba108b231e1",
"name": "Requirements1-task-1",
"assignee_id": "",
"start_date": "",
"end_date": ""
},
{
"id": "a1ce8762-5b54-4f63-af7d-95b8eb8e1576",
"name": "Requirements1-task-3",
"assignee_id": "",
"start_date": "",
"end_date": ""
},
{
"id": "62f877ae-07fc-472e-ad3a-0d2ff5c5a1ee",
"name": "Requirements1-task-2",
"assignee_id": "",
"start_date": "",
"end_date": ""
}
]
}
},
{
"mock1": {
"assignee_id": "",
"description": "",
"start_date": "24-02-01T05:51:02.768Z",
"end_date": "24-02-01T05:51:02.768Z",
"task_details": [
{ …
```

getUsecaseForm  new API

---

workflow/usecase/function.yml
workflow/usecase/getUsecaseAsset.js

This api getusecaseAsset it will get the asset view details 
pathparameters:
id: usecaseid:
response body :
```json
[
{
"mock1": [
{
"id": "7f00f35e-c223-4e98-b741-4afed36594b7",
"docName": "designImage",
"Url": "formkiq_url"
},
{
"id": "ec5e7579-9167-4c58-aaf5-47a192f5ad10",
"docName": "api specs",
"Url": "git.file"
}
]
},
{
"Requirements1": [
{
"id": "4a0622a9-7224-4730-bd49-a491be0daa8c",
"docName": "awsfile",
"Url": "aws_url"
},
{
"id": "342f7699-1212-4fd2-8669-441df2efe3fd",
"docName": "design.html",
"Url": "design_url"
}
]
}
]
```

getUsecaseAsset new API

---

workflow/usecase/addusecase.js

update: added start date ,end date in the stages 
responsebody:
```json
{
"usecase_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"project_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"created_by_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"usecase_name": "string",
"assigned_to_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
"description": "string"
}
```

AddUsecase update API

---

workflow/usecase/function.yml
workflow/usecase/getUsecasePlanning.js

**API name:** getUsecasePlanning
**Method:** get
**PathParameter:** usecase_id
**Description:**  This api gets task id, name,start_date,end_date,resource_start_date, resource_end_date for all the tasks correpsonding to a stage of a usecase. This API gets the required data for ScrumPlanning page view. 
```json
[
{
"Requirements1": {
"task_details": [
{
"id": "a1ce8762-5b54-4f63-af7d-95b8eb8e1576",
"name": "Requirements1-task-3",
"assignee_id": "",
"start_date": "",
"end_date": "",
"resource_start_date": "",
"resource_end_date": "",
"start_deviation": 0,
"end_deviation": 0
},
{
"id": "62f877ae-07fc-472e-ad3a-0d2ff5c5a1ee",
"name": "Requirements1-task-2",
"assignee_id": "",
"start_date": "",
"end_date": "",
"resource_start_date": "",
"resource_end_date": "", …
```

feat:added getUsecasePlanning  API

---

workflow/workflow/generateStateMachine.js

Description:
Just I updated the function to create the state machine definition 2
Before it is saving the task name like along with stage name - task name now it will save only the task name

Generatestatemachine2 function updated

---

workflow/metadocs/deleteMetaDoc.js
workflow/metadocs/function.yml

**API name:** deleteMetaDoc 
**Method:** DELETE
**Description:**  the primary functinality of this API is to delete the particular document from the metadocs_table.
**pathParameter:** document_id (required)
```json
{
"message": "document deleted"
}
```

feat:added deleteMetaDoc API

---

workflow/usecase/function.yml
workflow/usecase/updateChecklist.js

API name: updateChecklist
Method: PUT
Description: This API is to  update the checklist in stages to the inside usecase. Giving the usecase_id in the pathParams.
pathParameter: usecase_id (required)
Body:
``` json
{
"stage_name": "Requirements",
"item_id": 2,
"checked": true
}
```
Request body :
``` json
{
"checked": true,
"item_id": 2,
"description": "thing 2"
}
```

adding new api updateChecklist

---

workflow/task/addReply.js
workflow/task/function.yml

**API name:** addReply
**Method:** PUT
**Description:**  This api updates reply for the existing comment into comments column based on the index of the comment in the comments array. Every reply has the following structure 
```json
"reply": {
"comment": "reply11111",
"resource": {
"id": "26a677d9-133c-4f34-a553-5d977fd5f7f9",
"name": "shiva",
"image_url": ""
},
"created_date": "2024-01-30T05:00:30.561Z"
}
```
**pathParameter:** id (required)
**Request body :** 
```json 
{
"id": "26a677d9-133c-4f34-a553-5d977fd5f7f9",
"comment": "reply1",
"commentIndex": 0
}
```
```json
updated reply success
```

add: added addReply API for reply feature to the comments

---

workflow/resource/getResourcesByRole.js

**API name:** getResourcesByRole 
**Method:** GET
**Description:**  gets all the employee details based on designation passed in the request.
**queryParameter:** designation(required)
```json
[
{
"emp_id": "f7733e8d-5509-4851-b695-91ee4850a0b2",
"first_name": "ali",
"last_name": "ali",
"email": "a.ali@example.com",
"image": ""
}
]
```

feat:changed getResourcesByRole API

---

workflow/dashboard/getProjectResourceOverview.js
workflow/dashboard/getResourcesTasksStatus.js
workflow/project/getProjectTeam.js
workflow/project/projectsResourcesTasksStatus.js
workflow/resource/addResource.js
workflow/resource/getResources.js
workflow/resource/getResourcesByName.js
workflow/resource/getResourcesListView.js
workflow/task/addComment.js
workflow/task/addReply.js
workflow/task/completeTask.js
workflow/task/getTaskDocs.js
workflow/usecase/getUsecase.js
workflow/usecase/updateUsecase.js
workflow/workflow/updateWorkflow.js

Replaced resorce table to employee table

feat Replaced resorce table to employee table

---

workflow/project/getProjectTeam.js

added the designation in the response and modified the code according to the new db schema
request path paramenters project id 
Response body : 200 `
````json
[
{
"Backend-End Developer": [
{
"designation": "Backend-End Developer",
"resource_id": "be8ad3ba-45c1-4180-85e8-0082ab6724a1",
"first_name": "John",
"last_name": "Doe",
"image_url": "",
"email": "john.fsddoe@example.com"
},
{
"designation": "Backend-End Developer",
"resource_id": "f7733e8d-5509-4851-b695-91ee4850a0b2",
"first_name": "ali",
"last_name": "ali",
"image_url": "",
"email": "a.ali@example.com"
}
]
},
{
"Front-End Developer": [
{
"designation": "Front-End Developer",
"resource_id": "87a4b32a-2a9a-424a-a1a6-a95b6e6dafee",
"first_name": "rao",
"last_name": "Doe",
"image_url": "",
"email": "jhn.doe@example.com"
},
{ …
```

Updated getprojectteam API

---

workflow/dashboard/getResourcesTasksStatus.js

**API name:** getResourcesTasksStatus
**Changes:**
made minor change in the query.

refactor:minor changes in getResourcesTasksStatus

---

workflow/project/projectsResourcesTasksStatus.js
workflow/resource/getResourcesByName.js
workflow/resource/getResourcesByRole.js

modified the code according top the table structure and table names

Getresourcebyrole and get resource by name 

---

workflow/dashboard/getProjectResourceOverview.js

**API name:** getProjectResourceOverview 
**Method:** get
**QueryStringParameter:** status[optional]
**Description:**  This API gets all the employees of all the projects , We can also filter based on status of the project.
**API Response:** 
```json
[
{
"project_id": "56561553-fb6b-44e6-9680-9f26a96b075f",
"project_name": "tekton",
"project_resources": []
},
{
"project_id": "65a124c2-de98-43f2-a3c9-052769d88f52",
"project_name": "Mock",
"project_resources": [
{
"resource_id": "21b471ae-c1ff-4609-bbce-efe22a78f6c3",
"resource_name": "John Doe",
"image_url": "",
"email": "john.dofdgfddgdgfdfgdse@workplace.com",
"current_task": "TEstingSubStage",
"designation": "Project Manager",
"created_date": "2024-03-01",
"due_date": "",
"total_tasks": "2"
},
{
"resource_id": …
```

feat:modified getProjectResourceOverview API

---

workflow/task/completeTask.js
workflow/workflow/addWorkflow.js
workflow/workflow/generateStateMachine.js

This commit has the changes in the add workflow api and generatestatemachine functions 1 and 2 and modified task complete api

feat : Updated createstatemachine function and add workflow

---

workflow/workflow/getAllWorkflows.js

**API name:** getAllWorkflows 
**API Response:** 
```json
[
{
"id": "672f7d5f-0182-4bc1-8f42-ea19b17aa55c",
"name": "functions",
"stages": [
{
"name": "funcky",
"tasks": [
"zootopia"
],
"checklist": []
},
{
"name": "elephits",
"tasks": [
"zod"
],
"checklist": []
}
],
"created_by": {
"id": "21b471ae-c1ff-4609-bbce-efe22a78f6c3",
"first_name": "John",
"last_name": "Doe",
"designation": "Project Manager",
"image": ""
}
},
{
"id": "65fcd274-d5ec-4070-bfd5-319bc2c4eab6",
"name": "TestingTepper",
"stages": [
{
"name": "Required",
"tasks": [
"RequiredSubStage"
],
"checklist": []
}
],
"created_by": {
"id": "21b471ae-c1ff-4609-bbce-efe22a78f6c3",
"first_name": "John",
"last_name": "Doe",
"designation": "Project Manager",
"image": ""
}
},
{
"id": "eeb9269b-8d29-42ee-a8e7-95fe3db63bcf",
"name": …
```

feat:modified getAllWorkflows API to get created_by details

---

workflow/package-lock.json
workflow/package.json
workflow/task/function.yml
workflow/task/getTask.js
workflow/usecase/function.yml
workflow/usecase/getUsecase.js
workflow/usecase/getUsecaseTask.js

1. This pull request includes modifications to the YAML files task/function.yml and usecase/function.yml. These modifications enhance the configuration and functionality of the application.
2. task/getTask: This API retrieves task details.
3. usecase/getUsecaseTask: This API retrieves task details along with related documents for a specific use case.
4. modifications have been made to the usecase/getUsecase API to enhance its functionality and better integrate with the overall system.

feat:Modified YAML files and added  two APIs

---

workflow/usecase/getUsecaseTask.js

just changes to structure of the response 
````json
[ 
{
"task_id": "9575b644-71c8-4cec-bc2e-29ddc77982dd",
"task_name": "MockTestingsubStage2",
"status": "inprogress",
"assigned_to": {
"assignee_id": "",
"image": "",
"assignee_name": " ",
"assignee_designation": ""
},
"docs": [
{
"doc_name": "pdf3.file",
"doc_id": "a9057a5e-8155-4771-9820-8777eb5ea6b1",
"doc_url": "https:/pdf3",
"created_time": "2024-03-12T18:30:00"
}
]
},
{
"task_id": "9f21ffa1-cd6e-4216-942a-89518f2d2e1c",
"task_name": "RequiredSubStage2",
"status": "inprogress",
"assigned_to": {
"assignee_id": "",
"image": "",
"assignee_name": " ",
"assignee_designation": ""
},
"docs": [
{
"doc_name": "pdf7.file",
"doc_id": "e59a5a87-250c-47a5-a6c7-ea25769c2510",
"doc_url": "https:/pdf7",
"created_time": "2024-03-12T22:30:00"
}
]
},
{ …
```

fix: restructured the response

---

workflow/usecase/getUsecaseTask.js

Added employee_details in the response

getUsecaseTask API

---

workflow/usecase/getUsecasePlanning.js

**API name:** getUsecasePlanning
**API Response:** 
```json
[
{
"funcky": {
"task": [
{
"id": "fad582c0-2a69-4055-b40e-d88efd0f48d9",
"name": "zootopia",
"assigned_to": {
"id": "75e713d1-afa7-4d01-a3ad-3406d91dac83",
"name": "shfd3h srhf2ah",
"designation": "Project Manager",
"image": ""
},
"start_date": "",
"end_date": "",
"resource_start_date": "",
"resource_end_date": "",
"start_deviation": 0,
"end_deviation": 0
}
]
}
},
{
"elephits": {
"task": [
{
"id": "7e892167-b6e7-4e67-86a6-4f920a1486c2",
"name": "zod",
"assigned_to": {
"id": "21b471ae-c1ff-4609-bbce-efe22a78f6c3",
"name": "John Doe",
"designation": null,
"image": ""
},
"start_date": "",
"end_date": "",
"resource_start_date": "",
"resource_end_date": "",
"start_deviation": 0,
"end_deviation": 0
}
]
}
}
]
```

made minor changes in the response

---

workflow/project/getProjectTeam.js
workflow/workflow/addWorkflow.js
workflow/workflow/getWorkflow.js
workflow/workflow/updateWorkflow.js

refactor: minor changes

---

.prettierrc.json
package-lock.json
package.json
workflow/.prettierrc.json
workflow/package-lock.json
workflow/package.json
workflow/project/addProject.js
workflow/project/addTeamToProject.js
workflow/project/getProject.js
workflow/project/getProjectTeam.js
workflow/project/getProjectWorkflows.js
workflow/project/getProjects.js
workflow/project/projectsResourcesTasksStatus.js
workflow/util/authorizer.js
workflow/util/bodyValidator.js
workflow/util/errorHandler.js
workflow/util/pathParamsValidator.js
workflow/util/queryParamsValidator.js

Updated APIs

---

.prettierrc.json
package-lock.json
package.json
workflow/.prettierrc.json
workflow/package-lock.json
workflow/package.json
workflow/project/addProject.js
workflow/project/addTeamToProject.js
workflow/project/getProject.js
workflow/project/getProjectTeam.js
workflow/project/getProjectWorkflows.js
workflow/project/getProjects.js
workflow/project/projectsResourcesTasksStatus.js
workflow/util/authorizer.js
workflow/util/bodyValidator.js
workflow/util/errorHandler.js
workflow/util/pathParamsValidator.js
workflow/util/queryParamsValidator.js

Authentication and middy applied to projects folder

Authentication and middy applied to projects folder 

---

workflow/project/addProject.js
workflow/project/addTeamToProject.js
workflow/project/getProject.js
workflow/project/getProjectTeam.js
workflow/project/getProjectWorkflows.js
workflow/project/getProjects.js
workflow/project/projectsResourcesTasksStatus.js

update:Added authentication and middy/core

update:Added authentication and middy/core

---

workflow/task/addComment.js
workflow/task/addReply.js
workflow/task/assignTask.js
workflow/task/completeTask.js
workflow/task/deleteMetaDoc.js
workflow/task/function.yml
workflow/task/uploadMetaDoc.js

Updated the Authentication and Middleware in the task folder.

feat: Adding middleware and authentication

---

workflow/dashboard/getOrgProjectDetails.js
workflow/resource/getResources.js
workflow/resource/getResourcesByRole.js
workflow/workflow/addWorkflow.js
workflow/workflow/deleteWorkflow.js
workflow/workflow/getAllWorkflows.js
workflow/workflow/getWorkflow.js
workflow/workflow/updateWorkflow.js

**APIs modified**
getResources
getResourcesByRole
addWorkflow
deleteWorkflow
getAllWorkflows
getWorkflow
updateWorkflow

feat:added middleware for workflow,resource APIs

---

workflow/dashboard/getProjectResourceOverview.js
workflow/dashboard/getProjectsOverview.js
workflow/dashboard/getProjectsUsecaseOverview.js
workflow/dashboard/getResourcesTasksStatus.js
workflow/util/optionalParamsValidator.js

1. getProjectResourceOverview
2. getProjectsOverview
3. getProjectsUsecaseOverview
4. getResourcesTasksStatus

feat:Added middy to dashboards APIs

---

workflow/project/getProjects.js

API Responce:
```
{
"totalPages": 1,
"currentPage": 1,
"projects": [
{
"id": "14feeae9-c9c7-4fa0-939a-b9beba27b9c6",
"name": "TaskMaster",
"status": "unassigned",
"total_resources": 0,
"total_usecases": 0
},
{
"id": "465dca02-0f13-4bbf-879e-635a2edf5f89",
"name": "Geoffrey Tanner",
"status": "unassigned",
"total_resources": 2,
"total_usecases": 0
},
{
"id": "5150236d-01f7-4d5b-b8db-546207b157f7",
"name": "rftgyhuj",
"status": "unassigned",
"total_resources": 2,
"total_usecases": 0
},
{
"id": "6c75a69e-0a7c-414c-b5a7-accd60f71d07",
"name": "DemoTesting",
"status": "unassigned",
"total_resources": 1,
"total_usecases": 0
},
{
"id": "95d9ec60-ea2e-4397-afc8-7e0a967dfbf5",
"name": "https://workflow.synectiks.net/",
"status": "unassigned",
"total_resources": 1,
"total_usecases": 0
},
{
"id": …
```

feat: Added Pagination logic to getProjects API

---

workflow/project/addProject.js

Description : 
Added the org_id which is caught in the event and passing that id in to data base projects_table

Added org_id in the add project ApI

---

workflow/resource/getResources.js
workflow/workflow/addWorkflow.js
workflow/workflow/deleteWorkflow.js
workflow/workflow/getAllWorkflows.js

**addResources**
**addWorkflow**
**getAllWorkflows**
added org_id for necessary queries for above API's

feat:added org_id for workflow APIs

---

workflow/dashboard/getOrgProjectDetails.js

API Responce:
```
{
"total_projects": 2,
"total_tasks": 16,
"percentage_completed": 0,
"completed": 0,
"in_progress": 0,
"unassigned": 2
}
```

feat: Added org_id filter to getOrgProjectDetails in dashboards

---

workflow/project/projectsResourcesTasksStatus.js

handled the error when no data present in the teams

handled the error when no data present in the teams

---

workflow/usecase/assignStage.js
workflow/usecase/getUsecaseAsset.js

updated code according to the new ui
1.getUsecaseAsset 
2.Assign Stage

updated code according to the new ui

---

workflow/usecase/assignStage.js
workflow/usecase/getUsecaseAsset.js

updated the response according to ui

updated the response according to ui

---

workflow/project/getProjects.js

API Responce:
```json
{
"totalPages": 1,
"currentPage": 1,
"projects": [
{
"id": "9d744648-ff39-4ef2-9a31-8799ca083946",
"name": "Evelyn Colon",
"image_url": "https://i.imgur.com/PujQY5Y.png",
"status": "unassigned",
"total_resources": 2,
"total_usecases": 0
},
{
"id": "d5ce8820-5a3d-4e84-bf9a-64c4cd23efc0",
"name": "Demetria Cortez",
"image_url": "https://i.imgur.com/PujQY5Y.png",
"status": "completed",
"total_resources": 2,
"total_usecases": 0
}
]
}
```

feat: Added pagination to getProjects API

---

workflow/package-lock.json
workflow/package.json
workflow/task/uploadDocs.js
workflow/task/uploadMetaDoc.js
workflow/usecase/getUsecaseTask.js

**added uploadDocs function in task folder
Added type field on insert query of uplaodMetaDoc  API for type of document been uploaded
modified the getUsecaseTask API to return even the type of document**

feat:added uploadDocs function & modified uploadMetadoc API

---

workflow/task/completeTask.js
workflow/usecase/addusecase.js
workflow/usecase/assignStage.js
workflow/usecase/getUsecaseAsset.js

minor : included the new field status in the stages

minor : included the new field status in the stages

---

workflow/workflow/addTemplate.js
workflow/workflow/addWorkflow.js
workflow/workflow/function.yml

**API name :** addWorkflow
**API Request:** 
```
{
"name": "new_workflow12",
"created_by_id": "5450cdf0-63e6-467c-b1b9-08bab69420a9",
"project_id": "242380f0-62cb-4674-8a78-1e40a5341909",
"template_id": "1"
}
```
**API Response:**
```
{
"id": "8ac633d1-bb29-443c-8099-ced99ebc8607",
"metadata": {
"stages": [
{
"name": "Requirement",
"tasks": [
"Research",
"Usecase writting",
"Designing"
],
"checklist": []
},
{
"name": "MOCK Development",
"tasks": [
"API Specifications ",
"UI Code",
"Test Plans"
],
"checklist": []
}
],
"status": "inprogress",
"created_by": "5450cdf0-63e6-467c-b1b9-08bab69420a9",
"updated_by": "5450cdf0-63e6-467c-b1b9-08bab69420a9",
"created_time": "2024-04-09T08:36:53.814Z"
},
"name": "6783b1cb10be@new_workflow12",
"arn": …
```

feat:added template feature to addWorkflow API

---

workflow/upload/docUpload.js
workflow/upload/function.yaml
workflow/util/uploadDocs.js
workflow/workflow/addTemplate.js
workflow/workflow/template.js

new file:   upload/docUpload.js
new file:   upload/function.yaml
new file:   util/uploadDocs.js
new file:   workflow/addTemplate.js
new file:   workflow/template.js

feat: Added features from main branch

---

workflow/workflow/addTemplate.js

modified the code and removed the un wanted validation and this api is saving the workflow name as the template name changed to now it will save by the project name

minor : updated api
